version: '3'

services:
  frontend_thealfastore:
    container_name: frontend-alfastore
    image: frontend-alfastore
    restart: always
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=https://api.alfastoreargentina.com